// Auto-generated by scripts/fetch-recipe-art.mjs — do not hand-edit.
// Images generated by the Gemini API (gemini-2.5-flash-image), saved under public/recipe-art/.
// Keyed by recipe id. Screens fall back to the recipe emoji when an id has no entry.

export interface RecipeImage {
  url: string;
}

export const RECIPE_IMAGES: Record<string, RecipeImage> = {
  "arroz-feijao-simples": {
    "url": "/recipe-art/arroz-feijao-simples.jpg"
  },
  "feijao-preto-temperado": {
    "url": "/recipe-art/feijao-preto-temperado.jpg"
  },
  "frango-grelhado-limao": {
    "url": "/recipe-art/frango-grelhado-limao.jpg"
  },
  "frango-milanesa": {
    "url": "/recipe-art/frango-milanesa.jpg"
  },
  "frango-xadrez": {
    "url": "/recipe-art/frango-xadrez.jpg"
  },
  "frango-curry": {
    "url": "/recipe-art/frango-curry.jpg"
  },
  "coxa-frango-assada": {
    "url": "/recipe-art/coxa-frango-assada.jpg"
  },
  "bife-acebolado": {
    "url": "/recipe-art/bife-acebolado.jpg"
  },
  "picadinho-carne": {
    "url": "/recipe-art/picadinho-carne.jpg"
  },
  "carne-panela": {
    "url": "/recipe-art/carne-panela.jpg"
  },
  "escondidinho-carne-seca": {
    "url": "/recipe-art/escondidinho-carne-seca.jpg"
  },
  "bacon-ovos": {
    "url": "/recipe-art/bacon-ovos.jpg"
  },
  "omelete-queijo": {
    "url": "/recipe-art/omelete-queijo.jpg"
  },
  "ovos-mexidos-tomate": {
    "url": "/recipe-art/ovos-mexidos-tomate.jpg"
  },
  "salsicha-acebolada": {
    "url": "/recipe-art/salsicha-acebolada.jpg"
  },
  "linguica-acebolada": {
    "url": "/recipe-art/linguica-acebolada.jpg"
  },
  "costela-barbecue": {
    "url": "/recipe-art/costela-barbecue.jpg"
  },
  "lombo-assado-batatas": {
    "url": "/recipe-art/lombo-assado-batatas.jpg"
  },
  "peixe-frito": {
    "url": "/recipe-art/peixe-frito.jpg"
  },
  "peixe-assado-limao": {
    "url": "/recipe-art/peixe-assado-limao.jpg"
  },
  "salmao-grelhado": {
    "url": "/recipe-art/salmao-grelhado.jpg"
  },
  "atum-macarrao": {
    "url": "/recipe-art/atum-macarrao.jpg"
  },
  "sardinha-panela": {
    "url": "/recipe-art/sardinha-panela.jpg"
  },
  "camarao-alho-oleo": {
    "url": "/recipe-art/camarao-alho-oleo.jpg"
  },
  "moqueca-simples": {
    "url": "/recipe-art/moqueca-simples.jpg"
  },
  "macarrao-alho-oleo": {
    "url": "/recipe-art/macarrao-alho-oleo.jpg"
  },
  "macarrao-sugo": {
    "url": "/recipe-art/macarrao-sugo.jpg"
  },
  "macarrao-frango": {
    "url": "/recipe-art/macarrao-frango.jpg"
  },
  "nhoque-batata": {
    "url": "/recipe-art/nhoque-batata.jpg"
  },
  "risoto-frango": {
    "url": "/recipe-art/risoto-frango.jpg"
  },
  "arroz-forno": {
    "url": "/recipe-art/arroz-forno.jpg"
  },
  "feijoada-simplificada": {
    "url": "/recipe-art/feijoada-simplificada.jpg"
  },
  "sopa-legumes": {
    "url": "/recipe-art/sopa-legumes.jpg"
  },
  "canja-galinha": {
    "url": "/recipe-art/canja-galinha.jpg"
  },
  "pure-batata": {
    "url": "/recipe-art/pure-batata.jpg"
  },
  "batata-doce-assada": {
    "url": "/recipe-art/batata-doce-assada.jpg"
  },
  "legumes-refogados": {
    "url": "/recipe-art/legumes-refogados.jpg"
  },
  "abobrinha-recheada": {
    "url": "/recipe-art/abobrinha-recheada.jpg"
  },
  "berinjela-parmegiana": {
    "url": "/recipe-art/berinjela-parmegiana.jpg"
  },
  "salada-tomate-cebola": {
    "url": "/recipe-art/salada-tomate-cebola.jpg"
  },
  "salada-verde": {
    "url": "/recipe-art/salada-verde.jpg"
  },
  "salada-grao-bico": {
    "url": "/recipe-art/salada-grao-bico.jpg"
  },
  "salada-atum": {
    "url": "/recipe-art/salada-atum.jpg"
  },
  "vinagrete": {
    "url": "/recipe-art/vinagrete.jpg"
  },
  "farofa-simples": {
    "url": "/recipe-art/farofa-simples.jpg"
  },
  "polenta-cremosa": {
    "url": "/recipe-art/polenta-cremosa.jpg"
  },
  "pipoca-simples": {
    "url": "/recipe-art/pipoca-simples.jpg"
  },
  "aveia-banana": {
    "url": "/recipe-art/aveia-banana.jpg"
  },
  "salada-frutas": {
    "url": "/recipe-art/salada-frutas.jpg"
  },
  "vitamina-abacate": {
    "url": "/recipe-art/vitamina-abacate.jpg"
  },
  "macarrao-molho-branco": {
    "url": "/recipe-art/macarrao-molho-branco.jpg"
  },
  "frango-barbecue": {
    "url": "/recipe-art/frango-barbecue.jpg"
  },
  "costelinha-agridoce": {
    "url": "/recipe-art/costelinha-agridoce.jpg"
  },
  "salpicao-frango": {
    "url": "/recipe-art/salpicao-frango.jpg"
  },
  "omelete-espinafre": {
    "url": "/recipe-art/omelete-espinafre.jpg"
  },
  "sopa-ervilha": {
    "url": "/recipe-art/sopa-ervilha.jpg"
  },
  "risoto-camarao": {
    "url": "/recipe-art/risoto-camarao.jpg"
  },
  "sufle-brocolis": {
    "url": "/recipe-art/sufle-brocolis.jpg"
  },
  "couve-refogada": {
    "url": "/recipe-art/couve-refogada.jpg"
  },
  "salada-repolho": {
    "url": "/recipe-art/salada-repolho.jpg"
  },
  "palmito-molho-branco": {
    "url": "/recipe-art/palmito-molho-branco.jpg"
  },
  "salada-palmito": {
    "url": "/recipe-art/salada-palmito.jpg"
  },
  "brigadeiro": {
    "url": "/recipe-art/brigadeiro.jpg"
  },
  "bolo-cenoura-chocolate": {
    "url": "/recipe-art/bolo-cenoura-chocolate.jpg"
  },
  "bolo-chocolate-molhadinho": {
    "url": "/recipe-art/bolo-chocolate-molhadinho.jpg"
  },
  "pudim-leite-condensado": {
    "url": "/recipe-art/pudim-leite-condensado.jpg"
  },
  "bolinho-chuva": {
    "url": "/recipe-art/bolinho-chuva.jpg"
  },
  "bolo-fuba-cremoso": {
    "url": "/recipe-art/bolo-fuba-cremoso.jpg"
  },
  "pao-de-queijo": {
    "url": "/recipe-art/pao-de-queijo.jpg"
  },
  "coxinha-frango": {
    "url": "/recipe-art/coxinha-frango.jpg"
  },
  "misto-quente": {
    "url": "/recipe-art/misto-quente.jpg"
  },
  "pastel-forno-carne": {
    "url": "/recipe-art/pastel-forno-carne.jpg"
  },
  "lasanha-bolonhesa": {
    "url": "/recipe-art/lasanha-bolonhesa.jpg"
  },
  "panqueca-carne-moida": {
    "url": "/recipe-art/panqueca-carne-moida.jpg"
  },
  "torta-frango-liquidificador": {
    "url": "/recipe-art/torta-frango-liquidificador.jpg"
  },
  "chocolate-quente-cremoso": {
    "url": "/recipe-art/chocolate-quente-cremoso.jpg"
  },
  "suco-laranja-natural": {
    "url": "/recipe-art/suco-laranja-natural.jpg"
  },
  "vitamina-banana": {
    "url": "/recipe-art/vitamina-banana.jpg"
  },
  "suco-verde-detox": {
    "url": "/recipe-art/suco-verde-detox.jpg"
  },
  "cocada-cremosa": {
    "url": "/recipe-art/cocada-cremosa.jpg"
  },
  "beijinho": {
    "url": "/recipe-art/beijinho.jpg"
  },
  "mousse-chocolate": {
    "url": "/recipe-art/mousse-chocolate.jpg"
  },
  "danoninho-caseiro": {
    "url": "/recipe-art/danoninho-caseiro.jpg"
  },
  "sanduiche-natural-frango": {
    "url": "/recipe-art/sanduiche-natural-frango.jpg"
  },
  "pizza-liquidificador": {
    "url": "/recipe-art/pizza-liquidificador.jpg"
  },
  "arroz-doce": {
    "url": "/recipe-art/arroz-doce.jpg"
  },
  "frango-assado-ervas": {
    "url": "/recipe-art/frango-assado-ervas.jpg"
  },
  "picanha-chapa": {
    "url": "/recipe-art/picanha-chapa.jpg"
  },
  "carne-sol-abobora-coentro": {
    "url": "/recipe-art/carne-sol-abobora-coentro.jpg"
  },
  "carne-porco-refogada-cominho": {
    "url": "/recipe-art/carne-porco-refogada-cominho.jpg"
  },
  "pernil-assado-alecrim": {
    "url": "/recipe-art/pernil-assado-alecrim.jpg"
  },
  "mortadela-chapa": {
    "url": "/recipe-art/mortadela-chapa.jpg"
  },
  "figado-acebolado": {
    "url": "/recipe-art/figado-acebolado.jpg"
  },
  "peru-assado-natal": {
    "url": "/recipe-art/peru-assado-natal.jpg"
  },
  "posta-atum-grelhado": {
    "url": "/recipe-art/posta-atum-grelhado.jpg"
  },
  "arroz-integral-legumes": {
    "url": "/recipe-art/arroz-integral-legumes.jpg"
  },
  "feijao-fradinho-bacon": {
    "url": "/recipe-art/feijao-fradinho-bacon.jpg"
  },
  "salada-lentilha-legumes": {
    "url": "/recipe-art/salada-lentilha-legumes.jpg"
  },
  "salada-quinoa-grao-bico": {
    "url": "/recipe-art/salada-quinoa-grao-bico.jpg"
  },
  "salada-milho-ervilha": {
    "url": "/recipe-art/salada-milho-ervilha.jpg"
  },
  "sardinha-enlatada-cebola-tomate": {
    "url": "/recipe-art/sardinha-enlatada-cebola-tomate.jpg"
  },
  "feijao-grao-bico-enlatados": {
    "url": "/recipe-art/feijao-grao-bico-enlatados.jpg"
  },
  "salpicao-seleta-legumes": {
    "url": "/recipe-art/salpicao-seleta-legumes.jpg"
  },
  "strogonoff-cogumelos": {
    "url": "/recipe-art/strogonoff-cogumelos.jpg"
  },
  "pessego-calda-creme": {
    "url": "/recipe-art/pessego-calda-creme.jpg"
  },
  "bolo-laranja-margarina": {
    "url": "/recipe-art/bolo-laranja-margarina.jpg"
  },
  "peixe-molho-acafrao": {
    "url": "/recipe-art/peixe-molho-acafrao.jpg"
  },
  "limonada-hortela": {
    "url": "/recipe-art/limonada-hortela.jpg"
  },
  "frango-empanado-alho-po": {
    "url": "/recipe-art/frango-empanado-alho-po.jpg"
  },
  "compota-maca-cravo-canela": {
    "url": "/recipe-art/compota-maca-cravo-canela.jpg"
  },
  "pure-batata-noz-moscada": {
    "url": "/recipe-art/pure-batata-noz-moscada.jpg"
  },
  "batata-rustica-paprica": {
    "url": "/recipe-art/batata-rustica-paprica.jpg"
  },
  "macarrao-molho-rose": {
    "url": "/recipe-art/macarrao-molho-rose.jpg"
  },
  "macarrao-pesto": {
    "url": "/recipe-art/macarrao-pesto.jpg"
  },
  "bife-molho-ingles": {
    "url": "/recipe-art/bife-molho-ingles.jpg"
  },
  "frango-molho-pimenta-mel": {
    "url": "/recipe-art/frango-molho-pimenta-mel.jpg"
  },
  "pao-alho-molho-alho": {
    "url": "/recipe-art/pao-alho-molho-alho.jpg"
  },
  "salada-vinagrete-simples": {
    "url": "/recipe-art/salada-vinagrete-simples.jpg"
  },
  "sopa-raizes": {
    "url": "/recipe-art/sopa-raizes.jpg"
  },
  "refogado-folhas-variadas": {
    "url": "/recipe-art/refogado-folhas-variadas.jpg"
  },
  "legumes-assados-ervas-2": {
    "url": "/recipe-art/legumes-assados-ervas-2.jpg"
  },
  "quiabo-jilo-refogados": {
    "url": "/recipe-art/quiabo-jilo-refogados.jpg"
  },
  "salada-rabanete-gengibre": {
    "url": "/recipe-art/salada-rabanete-gengibre.jpg"
  },
  "salada-tropical-frutas": {
    "url": "/recipe-art/salada-tropical-frutas.jpg"
  },
  "compota-frutas-vermelhas": {
    "url": "/recipe-art/compota-frutas-vermelhas.jpg"
  },
  "suco-detox-caju-acerola": {
    "url": "/recipe-art/suco-detox-caju-acerola.jpg"
  },
  "salada-frutas-goiaba-pessego-lichia": {
    "url": "/recipe-art/salada-frutas-goiaba-pessego-lichia.jpg"
  },
  "sobrecoxa-assada": {
    "url": "/recipe-art/sobrecoxa-assada.jpg"
  },
  "asa-frango-mel-soja": {
    "url": "/recipe-art/asa-frango-mel-soja.jpg"
  },
  "coracao-frango-espeto": {
    "url": "/recipe-art/coracao-frango-espeto.jpg"
  },
  "file-mignon-ervas": {
    "url": "/recipe-art/file-mignon-ervas.jpg"
  },
  "patinho-molho-cebola": {
    "url": "/recipe-art/patinho-molho-cebola.jpg"
  },
  "contrafile-chapa": {
    "url": "/recipe-art/contrafile-chapa.jpg"
  },
  "maminha-assada": {
    "url": "/recipe-art/maminha-assada.jpg"
  },
  "fraldinha-churrasqueira": {
    "url": "/recipe-art/fraldinha-churrasqueira.jpg"
  },
  "cupim-panela-pressao": {
    "url": "/recipe-art/cupim-panela-pressao.jpg"
  },
  "lagarto-rosbife-mostarda": {
    "url": "/recipe-art/lagarto-rosbife-mostarda.jpg"
  },
  "acem-cozido-legumes": {
    "url": "/recipe-art/acem-cozido-legumes.jpg"
  },
  "musculo-molho-tomate": {
    "url": "/recipe-art/musculo-molho-tomate.jpg"
  },
  "costelinha-suina-mel-mostarda": {
    "url": "/recipe-art/costelinha-suina-mel-mostarda.jpg"
  },
  "panceta-crocante": {
    "url": "/recipe-art/panceta-crocante.jpg"
  },
  "bisteca-grelhada-limao": {
    "url": "/recipe-art/bisteca-grelhada-limao.jpg"
  },
  "espaguete-a-carbonara": {
    "url": "/recipe-art/espaguete-a-carbonara.jpg"
  },
  "mousse-de-banana": {
    "url": "/recipe-art/mousse-de-banana.jpg"
  },
  "avocado-toast-ovo-poche": {
    "url": "/recipe-art/avocado-toast-ovo-poche.jpg"
  },
  "banana-toast": {
    "url": "/recipe-art/banana-toast.jpg"
  },
  "bauru-de-forno": {
    "url": "/recipe-art/bauru-de-forno.jpg"
  },
  "geladinho-de-abacaxi": {
    "url": "/recipe-art/geladinho-de-abacaxi.jpg"
  },
  "rosquinha-de-leite-frita": {
    "url": "/recipe-art/rosquinha-de-leite-frita.jpg"
  },
  "torta-fria-de-frango": {
    "url": "/recipe-art/torta-fria-de-frango.jpg"
  },
  "feijao-de-coco": {
    "url": "/recipe-art/feijao-de-coco.jpg"
  },
  "palha-italiana": {
    "url": "/recipe-art/palha-italiana.jpg"
  },
  "torta-limao-sem-forno": {
    "url": "/recipe-art/torta-limao-sem-forno.jpg"
  },
  "brownie-chocolate": {
    "url": "/recipe-art/brownie-chocolate.jpg"
  },
  "bolo-milho-cremoso": {
    "url": "/recipe-art/bolo-milho-cremoso.jpg"
  },
  "curau-milho-verde": {
    "url": "/recipe-art/curau-milho-verde.jpg"
  },
  "bolo-banana-canela": {
    "url": "/recipe-art/bolo-banana-canela.jpg"
  },
  "cheesecake-morango-geladeira": {
    "url": "/recipe-art/cheesecake-morango-geladeira.jpg"
  },
  "doce-abobora-coco": {
    "url": "/recipe-art/doce-abobora-coco.jpg"
  },
  "bananas-caramelizadas-canela": {
    "url": "/recipe-art/bananas-caramelizadas-canela.jpg"
  },
  "pipoca-doce-caramelizada": {
    "url": "/recipe-art/pipoca-doce-caramelizada.jpg"
  },
  "manga-iogurte-mel": {
    "url": "/recipe-art/manga-iogurte-mel.jpg"
  },
  "banana-frita-canela": {
    "url": "/recipe-art/banana-frita-canela.jpg"
  },
  "doce-batata-doce-coco": {
    "url": "/recipe-art/doce-batata-doce-coco.jpg"
  },
  "quindim": {
    "url": "/recipe-art/quindim.jpg"
  },
  "bolo-de-rolo": {
    "url": "/recipe-art/bolo-de-rolo.jpg"
  },
  "geladinho-morango": {
    "url": "/recipe-art/geladinho-morango.jpg"
  },
  "geladinho-maracuja": {
    "url": "/recipe-art/geladinho-maracuja.jpg"
  },
  "geladinho-coco": {
    "url": "/recipe-art/geladinho-coco.jpg"
  },
  "geladinho-uva": {
    "url": "/recipe-art/geladinho-uva.jpg"
  },
  "vitamina-morango": {
    "url": "/recipe-art/vitamina-morango.jpg"
  },
  "vitamina-mamao": {
    "url": "/recipe-art/vitamina-mamao.jpg"
  },
  "vitamina-manga": {
    "url": "/recipe-art/vitamina-manga.jpg"
  },
  "suco-abacaxi-hortela": {
    "url": "/recipe-art/suco-abacaxi-hortela.jpg"
  },
  "suco-melancia": {
    "url": "/recipe-art/suco-melancia.jpg"
  },
  "suco-maracuja": {
    "url": "/recipe-art/suco-maracuja.jpg"
  },
  "suco-uva-natural": {
    "url": "/recipe-art/suco-uva-natural.jpg"
  },
  "espetinho-frutas-mel": {
    "url": "/recipe-art/espetinho-frutas-mel.jpg"
  },
  "abacaxi-grelhado-canela": {
    "url": "/recipe-art/abacaxi-grelhado-canela.jpg"
  },
  "melancia-hortela-limao": {
    "url": "/recipe-art/melancia-hortela-limao.jpg"
  },
  "coco-gelado-leite-condensado": {
    "url": "/recipe-art/coco-gelado-leite-condensado.jpg"
  },
  "pudim-coco": {
    "url": "/recipe-art/pudim-coco.jpg"
  },
  "pudim-maracuja": {
    "url": "/recipe-art/pudim-maracuja.jpg"
  },
  "manjar-branco-calda-ameixa": {
    "url": "/recipe-art/manjar-branco-calda-ameixa.jpg"
  },
  "ambrosia-coco": {
    "url": "/recipe-art/ambrosia-coco.jpg"
  },
  "brigadeirao": {
    "url": "/recipe-art/brigadeirao.jpg"
  },
  "mousse-maracuja": {
    "url": "/recipe-art/mousse-maracuja.jpg"
  },
  "mousse-morango": {
    "url": "/recipe-art/mousse-morango.jpg"
  },
  "mousse-limao": {
    "url": "/recipe-art/mousse-limao.jpg"
  },
  "pave-chocolate": {
    "url": "/recipe-art/pave-chocolate.jpg"
  },
  "pave-morango": {
    "url": "/recipe-art/pave-morango.jpg"
  },
  "torta-bolacha-chocolate": {
    "url": "/recipe-art/torta-bolacha-chocolate.jpg"
  },
  "cheesecake-maracuja-geladeira": {
    "url": "/recipe-art/cheesecake-maracuja-geladeira.jpg"
  },
  "doce-leite-cremoso": {
    "url": "/recipe-art/doce-leite-cremoso.jpg"
  },
  "compota-pessego": {
    "url": "/recipe-art/compota-pessego.jpg"
  },
  "compota-abacaxi": {
    "url": "/recipe-art/compota-abacaxi.jpg"
  },
  "bolo-coco": {
    "url": "/recipe-art/bolo-coco.jpg"
  },
  "bolo-laranja-calda": {
    "url": "/recipe-art/bolo-laranja-calda.jpg"
  },
  "bolo-formigueiro": {
    "url": "/recipe-art/bolo-formigueiro.jpg"
  },
  "bolo-iogurte": {
    "url": "/recipe-art/bolo-iogurte.jpg"
  },
  "bolo-maca-canela": {
    "url": "/recipe-art/bolo-maca-canela.jpg"
  },
  "bolo-limao-glace": {
    "url": "/recipe-art/bolo-limao-glace.jpg"
  },
  "bolo-fuba-coco": {
    "url": "/recipe-art/bolo-fuba-coco.jpg"
  },
  "bolo-pe-de-moca": {
    "url": "/recipe-art/bolo-pe-de-moca.jpg"
  },
  "bolo-gelado-pernambuco": {
    "url": "/recipe-art/bolo-gelado-pernambuco.jpg"
  },
  "rocambole-doce-leite": {
    "url": "/recipe-art/rocambole-doce-leite.jpg"
  },
  "torta-holandesa-simples": {
    "url": "/recipe-art/torta-holandesa-simples.jpg"
  },
  "bolo-banana-aveia": {
    "url": "/recipe-art/bolo-banana-aveia.jpg"
  },
  "bolo-cenoura-simples": {
    "url": "/recipe-art/bolo-cenoura-simples.jpg"
  },
  "churros-caseiros": {
    "url": "/recipe-art/churros-caseiros.jpg"
  },
  "sonhos-recheados-creme": {
    "url": "/recipe-art/sonhos-recheados-creme.jpg"
  },
  "geladinho-manga": {
    "url": "/recipe-art/geladinho-manga.jpg"
  },
  "picole-caseiro-abacaxi-hortela": {
    "url": "/recipe-art/picole-caseiro-abacaxi-hortela.jpg"
  },
  "taca-morango-chantininho": {
    "url": "/recipe-art/taca-morango-chantininho.jpg"
  },
  "banana-com-mel-canela": {
    "url": "/recipe-art/banana-com-mel-canela.jpg"
  },
  "maca-assada-canela": {
    "url": "/recipe-art/maca-assada-canela.jpg"
  },
  "pera-cozida-mel": {
    "url": "/recipe-art/pera-cozida-mel.jpg"
  },
  "trufa-chocolate": {
    "url": "/recipe-art/trufa-chocolate.jpg"
  },
  "bombom-morango": {
    "url": "/recipe-art/bombom-morango.jpg"
  },
  "bombom-uva": {
    "url": "/recipe-art/bombom-uva.jpg"
  },
  "creme-abacate-cacau": {
    "url": "/recipe-art/creme-abacate-cacau.jpg"
  },
  "creme-manga-coco": {
    "url": "/recipe-art/creme-manga-coco.jpg"
  },
  "iogurte-frutas-vermelhas-mel": {
    "url": "/recipe-art/iogurte-frutas-vermelhas-mel.jpg"
  },
  "salada-frutas-citricas": {
    "url": "/recipe-art/salada-frutas-citricas.jpg"
  },
  "banana-caramelizada-forno": {
    "url": "/recipe-art/banana-caramelizada-forno.jpg"
  },
  "pipoca-doce-chocolate": {
    "url": "/recipe-art/pipoca-doce-chocolate.jpg"
  },
  "bolo-mandioca-coco": {
    "url": "/recipe-art/bolo-mandioca-coco.jpg"
  },
  "tapioca-doce-coco": {
    "url": "/recipe-art/tapioca-doce-coco.jpg"
  },
  "cocada-queimada": {
    "url": "/recipe-art/cocada-queimada.jpg"
  },
  "bolinho-coco-frito": {
    "url": "/recipe-art/bolinho-coco-frito.jpg"
  },
  "doce-mamao-coco": {
    "url": "/recipe-art/doce-mamao-coco.jpg"
  },
  "bolo-abacaxi-calda": {
    "url": "/recipe-art/bolo-abacaxi-calda.jpg"
  },
  "bolo-maracuja-cobertura": {
    "url": "/recipe-art/bolo-maracuja-cobertura.jpg"
  },
  "cheesecake-limao-geladeira": {
    "url": "/recipe-art/cheesecake-limao-geladeira.jpg"
  },
  "pudim-pao": {
    "url": "/recipe-art/pudim-pao.jpg"
  },
  "rosquinhas-acucar-canela-forno": {
    "url": "/recipe-art/rosquinhas-acucar-canela-forno.jpg"
  },
  "bolo-chocolate-cobertura-brigadeiro": {
    "url": "/recipe-art/bolo-chocolate-cobertura-brigadeiro.jpg"
  },
  "mousse-coco": {
    "url": "/recipe-art/mousse-coco.jpg"
  },
  "geleia-frutas-vermelhas-caseira": {
    "url": "/recipe-art/geleia-frutas-vermelhas-caseira.jpg"
  },
  "banana-split-caseiro": {
    "url": "/recipe-art/banana-split-caseiro.jpg"
  },
  "suco-caju": {
    "url": "/recipe-art/suco-caju.jpg"
  },
  "beijinho-limao": {
    "url": "/recipe-art/beijinho-limao.jpg"
  },
  "doce-abobora-cristalizada": {
    "url": "/recipe-art/doce-abobora-cristalizada.jpg"
  },
  "compota-goiaba": {
    "url": "/recipe-art/compota-goiaba.jpg"
  },
  "suco-goiaba": {
    "url": "/recipe-art/suco-goiaba.jpg"
  },
  "vitamina-abacaxi-coco": {
    "url": "/recipe-art/vitamina-abacaxi-coco.jpg"
  },
  "bolo-chocolate-banana": {
    "url": "/recipe-art/bolo-chocolate-banana.jpg"
  },
  "torta-maca-sem-forno": {
    "url": "/recipe-art/torta-maca-sem-forno.jpg"
  },
  "creme-maracuja-colher": {
    "url": "/recipe-art/creme-maracuja-colher.jpg"
  },
  "cocada-de-forno": {
    "url": "/recipe-art/cocada-de-forno.jpg"
  },
  "salada-frutas-mel-hortela": {
    "url": "/recipe-art/salada-frutas-mel-hortela.jpg"
  },
  "suco-manga-laranja": {
    "url": "/recipe-art/suco-manga-laranja.jpg"
  },
  "vitamina-coco-banana": {
    "url": "/recipe-art/vitamina-coco-banana.jpg"
  },
  "pudim-abacaxi": {
    "url": "/recipe-art/pudim-abacaxi.jpg"
  },
  "limonada-suica": {
    "url": "/recipe-art/limonada-suica.jpg"
  },
  "geladinho-de-morango-iogurte": {
    "url": "/recipe-art/geladinho-de-morango-iogurte.jpg"
  },
  "suspiro-forno": {
    "url": "/recipe-art/suspiro-forno.jpg"
  },
  "bolo-pudim-caseiro": {
    "url": "/recipe-art/bolo-pudim-caseiro.jpg"
  },
  "bananada": {
    "url": "/recipe-art/bananada.jpg"
  },
  "goiabada-caseira": {
    "url": "/recipe-art/goiabada-caseira.jpg"
  },
  "bolo-salame-chocolate": {
    "url": "/recipe-art/bolo-salame-chocolate.jpg"
  },
  "pipoca-doce-microondas": {
    "url": "/recipe-art/pipoca-doce-microondas.jpg"
  },
  "banana-airfryer-canela-mel": {
    "url": "/recipe-art/banana-airfryer-canela-mel.jpg"
  },
  "abacaxi-airfryer-canela": {
    "url": "/recipe-art/abacaxi-airfryer-canela.jpg"
  },
  "torta-banana-bolacha-sem-forno": {
    "url": "/recipe-art/torta-banana-bolacha-sem-forno.jpg"
  },
  "compota-cereja": {
    "url": "/recipe-art/compota-cereja.jpg"
  },
  "compota-ameixa": {
    "url": "/recipe-art/compota-ameixa.jpg"
  },
  "vitamina-kiwi-maca": {
    "url": "/recipe-art/vitamina-kiwi-maca.jpg"
  },
  "suco-acerola": {
    "url": "/recipe-art/suco-acerola.jpg"
  },
  "cheesecake-cereja": {
    "url": "/recipe-art/cheesecake-cereja.jpg"
  },
  "limonada-maracuja": {
    "url": "/recipe-art/limonada-maracuja.jpg"
  },
  "strogonoff-carne-moida": {
    "url": "/recipe-art/strogonoff-carne-moida.jpg"
  },
  "strogonoff-frango": {
    "url": "/recipe-art/strogonoff-frango.jpg"
  },
  "hamburguer-caseiro": {
    "url": "/recipe-art/hamburguer-caseiro.jpg"
  },
  "quibe-de-forno": {
    "url": "/recipe-art/quibe-de-forno.jpg"
  },
  "boi-atolado": {
    "url": "/recipe-art/boi-atolado.jpg"
  },
  "file-frango-parmegiana": {
    "url": "/recipe-art/file-frango-parmegiana.jpg"
  },
  "polenta-ragu-carne-linguica": {
    "url": "/recipe-art/polenta-ragu-carne-linguica.jpg"
  },
  "crepioca-salgada-queijo": {
    "url": "/recipe-art/crepioca-salgada-queijo.jpg"
  },
  "pao-tapioca-queijo": {
    "url": "/recipe-art/pao-tapioca-queijo.jpg"
  },
  "baiao-de-dois": {
    "url": "/recipe-art/baiao-de-dois.jpg"
  },
  "tutu-de-feijao": {
    "url": "/recipe-art/tutu-de-feijao.jpg"
  },
  "galinhada": {
    "url": "/recipe-art/galinhada.jpg"
  },
  "frango-com-quiabo": {
    "url": "/recipe-art/frango-com-quiabo.jpg"
  },
  "camarao-na-moranga": {
    "url": "/recipe-art/camarao-na-moranga.jpg"
  },
  "peixada-simples": {
    "url": "/recipe-art/peixada-simples.jpg"
  },
  "escondidinho-de-frango": {
    "url": "/recipe-art/escondidinho-de-frango.jpg"
  },
  "torta-palmito-liquidificador": {
    "url": "/recipe-art/torta-palmito-liquidificador.jpg"
  },
  "rocambole-de-carne": {
    "url": "/recipe-art/rocambole-de-carne.jpg"
  },
  "enroladinho-de-salsicha": {
    "url": "/recipe-art/enroladinho-de-salsicha.jpg"
  },
  "bolinho-de-peixe-frito": {
    "url": "/recipe-art/bolinho-de-peixe-frito.jpg"
  },
  "empadao-de-frango": {
    "url": "/recipe-art/empadao-de-frango.jpg"
  },
  "pastel-frito-de-queijo": {
    "url": "/recipe-art/pastel-frito-de-queijo.jpg"
  },
  "risole-presunto-queijo": {
    "url": "/recipe-art/risole-presunto-queijo.jpg"
  },
  "croquete-de-carne": {
    "url": "/recipe-art/croquete-de-carne.jpg"
  },
  "frango-molho-curry-tomate": {
    "url": "/recipe-art/frango-molho-curry-tomate.jpg"
  },
  "frango-teriyaki": {
    "url": "/recipe-art/frango-teriyaki.jpg"
  },
  "picanha-assada-forno-sal-grosso": {
    "url": "/recipe-art/picanha-assada-forno-sal-grosso.jpg"
  },
  "frango-ensopado-batata-baroa": {
    "url": "/recipe-art/frango-ensopado-batata-baroa.jpg"
  },
  "frango-a-camponesa": {
    "url": "/recipe-art/frango-a-camponesa.jpg"
  },
  "frango-leite-coco-gengibre": {
    "url": "/recipe-art/frango-leite-coco-gengibre.jpg"
  },
  "lasanha-frango-requeijao": {
    "url": "/recipe-art/lasanha-frango-requeijao.jpg"
  },
  "frango-recheado-farofa": {
    "url": "/recipe-art/frango-recheado-farofa.jpg"
  },
  "bobo-de-camarao": {
    "url": "/recipe-art/bobo-de-camarao.jpg"
  },
  "vatapa-de-camarao": {
    "url": "/recipe-art/vatapa-de-camarao.jpg"
  },
  "costela-bovina-pressao-legumes": {
    "url": "/recipe-art/costela-bovina-pressao-legumes.jpg"
  },
  "fondue-de-carne-molhos": {
    "url": "/recipe-art/fondue-de-carne-molhos.jpg"
  },
  "file-tilapia-grelhado-alho": {
    "url": "/recipe-art/file-tilapia-grelhado-alho.jpg"
  },
  "salmao-molho-mostarda-mel": {
    "url": "/recipe-art/salmao-molho-mostarda-mel.jpg"
  },
  "arroz-de-camarao": {
    "url": "/recipe-art/arroz-de-camarao.jpg"
  },
  "macarrao-camarao-alho-oleo": {
    "url": "/recipe-art/macarrao-camarao-alho-oleo.jpg"
  },
  "risoto-de-cogumelos": {
    "url": "/recipe-art/risoto-de-cogumelos.jpg"
  },
  "risoto-de-abobora": {
    "url": "/recipe-art/risoto-de-abobora.jpg"
  },
  "arroz-carreteiro": {
    "url": "/recipe-art/arroz-carreteiro.jpg"
  },
  "feijao-tropeiro": {
    "url": "/recipe-art/feijao-tropeiro.jpg"
  },
  "omelete-presunto-queijo": {
    "url": "/recipe-art/omelete-presunto-queijo.jpg"
  },
  "panqueca-frango-requeijao": {
    "url": "/recipe-art/panqueca-frango-requeijao.jpg"
  },
  "bife-a-role-recheado": {
    "url": "/recipe-art/bife-a-role-recheado.jpg"
  },
  "lombo-suino-molho-laranja": {
    "url": "/recipe-art/lombo-suino-molho-laranja.jpg"
  },
  "sufle-de-milho": {
    "url": "/recipe-art/sufle-de-milho.jpg"
  },
  "pure-batata-baroa": {
    "url": "/recipe-art/pure-batata-baroa.jpg"
  },
  "farofa-de-bacon": {
    "url": "/recipe-art/farofa-de-bacon.jpg"
  },
  "farofa-de-banana": {
    "url": "/recipe-art/farofa-de-banana.jpg"
  },
  "arroz-biro-biro": {
    "url": "/recipe-art/arroz-biro-biro.jpg"
  },
  "maionese-batata-cenoura-ervilha": {
    "url": "/recipe-art/maionese-batata-cenoura-ervilha.jpg"
  },
  "salada-caesar-frango-grelhado": {
    "url": "/recipe-art/salada-caesar-frango-grelhado.jpg"
  },
  "salada-pepino-iogurte": {
    "url": "/recipe-art/salada-pepino-iogurte.jpg"
  },
  "berinjela-grelhada-azeite-ervas": {
    "url": "/recipe-art/berinjela-grelhada-azeite-ervas.jpg"
  },
  "abobrinha-grelhada-parmesao": {
    "url": "/recipe-art/abobrinha-grelhada-parmesao.jpg"
  },
  "sopa-abobora-gengibre": {
    "url": "/recipe-art/sopa-abobora-gengibre.jpg"
  },
  "sopa-feijao-bacon": {
    "url": "/recipe-art/sopa-feijao-bacon.jpg"
  },
  "creme-de-milho-salgado": {
    "url": "/recipe-art/creme-de-milho-salgado.jpg"
  },
  "peixe-empanado-farinha-rosca": {
    "url": "/recipe-art/peixe-empanado-farinha-rosca.jpg"
  },
  "camarao-empanado-frito": {
    "url": "/recipe-art/camarao-empanado-frito.jpg"
  },
  "isca-frango-airfryer": {
    "url": "/recipe-art/isca-frango-airfryer.jpg"
  },
  "batata-frita-caseira-airfryer": {
    "url": "/recipe-art/batata-frita-caseira-airfryer.jpg"
  },
  "aneis-cebola-empanados": {
    "url": "/recipe-art/aneis-cebola-empanados.jpg"
  },
  "macarrao-linguica-brocolis": {
    "url": "/recipe-art/macarrao-linguica-brocolis.jpg"
  },
  "nhoque-molho-gorgonzola": {
    "url": "/recipe-art/nhoque-molho-gorgonzola.jpg"
  },
  "feijao-enlatado-bacon-ervas": {
    "url": "/recipe-art/feijao-enlatado-bacon-ervas.jpg"
  },
  "couve-com-bacon": {
    "url": "/recipe-art/couve-com-bacon.jpg"
  },
  "repolho-refogado-bacon": {
    "url": "/recipe-art/repolho-refogado-bacon.jpg"
  },
  "chuchu-refogado-bacon": {
    "url": "/recipe-art/chuchu-refogado-bacon.jpg"
  },
  "inhame-cozido-alho-azeite": {
    "url": "/recipe-art/inhame-cozido-alho-azeite.jpg"
  },
  "cara-refogado-manteiga": {
    "url": "/recipe-art/cara-refogado-manteiga.jpg"
  },
  "beterraba-cozida-vinagrete": {
    "url": "/recipe-art/beterraba-cozida-vinagrete.jpg"
  },
  "nabo-refogado-manteiga": {
    "url": "/recipe-art/nabo-refogado-manteiga.jpg"
  },
  "aspargo-grelhado-alho": {
    "url": "/recipe-art/aspargo-grelhado-alho.jpg"
  },
  "cogumelos-salteados-alho-ervas": {
    "url": "/recipe-art/cogumelos-salteados-alho-ervas.jpg"
  },
  "pimentao-recheado-arroz-carne": {
    "url": "/recipe-art/pimentao-recheado-arroz-carne.jpg"
  },
  "bolo-chocolate-panela-pressao": {
    "url": "/recipe-art/bolo-chocolate-panela-pressao.jpg"
  },
  "bolo-fuba-panela-pressao": {
    "url": "/recipe-art/bolo-fuba-panela-pressao.jpg"
  },
  "bolo-cenoura-panela-pressao-chocolate": {
    "url": "/recipe-art/bolo-cenoura-panela-pressao-chocolate.jpg"
  },
  "doce-leite-panela-pressao": {
    "url": "/recipe-art/doce-leite-panela-pressao.jpg"
  },
  "panqueca-americana-mel-chapa": {
    "url": "/recipe-art/panqueca-americana-mel-chapa.jpg"
  },
  "panqueca-banana-canela-chapa": {
    "url": "/recipe-art/panqueca-banana-canela-chapa.jpg"
  },
  "crepioca-doce-banana-canela": {
    "url": "/recipe-art/crepioca-doce-banana-canela.jpg"
  },
  "tapioca-doce-leite-morango-chapa": {
    "url": "/recipe-art/tapioca-doce-leite-morango-chapa.jpg"
  },
  "pao-doce-churrasqueira-doce-leite": {
    "url": "/recipe-art/pao-doce-churrasqueira-doce-leite.jpg"
  },
  "banana-grelhada-churrasqueira-canela-mel": {
    "url": "/recipe-art/banana-grelhada-churrasqueira-canela-mel.jpg"
  },
  "pessego-grelhado-churrasqueira-mel-canela": {
    "url": "/recipe-art/pessego-grelhado-churrasqueira-mel-canela.jpg"
  },
  "bolo-caneca-chocolate-microondas": {
    "url": "/recipe-art/bolo-caneca-chocolate-microondas.jpg"
  },
  "brigadeiro-microondas": {
    "url": "/recipe-art/brigadeiro-microondas.jpg"
  },
  "pudim-express-microondas": {
    "url": "/recipe-art/pudim-express-microondas.jpg"
  },
  "maca-recheada-microondas-aveia-canela": {
    "url": "/recipe-art/maca-recheada-microondas-aveia-canela.jpg"
  },
  "cookies-chocolate-aveia": {
    "url": "/recipe-art/cookies-chocolate-aveia.jpg"
  },
  "biscoito-amanteigado-simples": {
    "url": "/recipe-art/biscoito-amanteigado-simples.jpg"
  },
  "muffin-chocolate": {
    "url": "/recipe-art/muffin-chocolate.jpg"
  },
  "pao-de-mel-caseiro": {
    "url": "/recipe-art/pao-de-mel-caseiro.jpg"
  },
  "biscoito-polvilho-doce-assado": {
    "url": "/recipe-art/biscoito-polvilho-doce-assado.jpg"
  },
  "granola-caseira-assada-mel": {
    "url": "/recipe-art/granola-caseira-assada-mel.jpg"
  },
  "bolo-chocolate-cobertura-requeijao": {
    "url": "/recipe-art/bolo-chocolate-cobertura-requeijao.jpg"
  },
  "pacoca-amendoim-caseira": {
    "url": "/recipe-art/pacoca-amendoim-caseira.jpg"
  },
  "pe-de-moleque-amendoim": {
    "url": "/recipe-art/pe-de-moleque-amendoim.jpg"
  },
  "cajuzinho": {
    "url": "/recipe-art/cajuzinho.jpg"
  },
  "olho-de-sogra": {
    "url": "/recipe-art/olho-de-sogra.jpg"
  },
  "rabanada-tradicional": {
    "url": "/recipe-art/rabanada-tradicional.jpg"
  },
  "barra-cereal-caseira-sem-forno": {
    "url": "/recipe-art/barra-cereal-caseira-sem-forno.jpg"
  },
  "mingau-aveia-banana-canela": {
    "url": "/recipe-art/mingau-aveia-banana-canela.jpg"
  },
  "parfait-iogurte-frutas-vermelhas-granola": {
    "url": "/recipe-art/parfait-iogurte-frutas-vermelhas-granola.jpg"
  },
  "fondue-chocolate-frutas": {
    "url": "/recipe-art/fondue-chocolate-frutas.jpg"
  },
  "biscoito-nata-caseiro": {
    "url": "/recipe-art/biscoito-nata-caseiro.jpg"
  },
  "pao-doce-caseiro-rapido": {
    "url": "/recipe-art/pao-doce-caseiro-rapido.jpg"
  },
  "bolo-pote-doce-leite-bolacha": {
    "url": "/recipe-art/bolo-pote-doce-leite-bolacha.jpg"
  },
  "creme-mamao-leite-condensado": {
    "url": "/recipe-art/creme-mamao-leite-condensado.jpg"
  },
  "cuca-banana-farofa-doce": {
    "url": "/recipe-art/cuca-banana-farofa-doce.jpg"
  },
  "torta-limao-assada": {
    "url": "/recipe-art/torta-limao-assada.jpg"
  },
  "cheesecake-assado-chocolate": {
    "url": "/recipe-art/cheesecake-assado-chocolate.jpg"
  },
  "sufle-chocolate": {
    "url": "/recipe-art/sufle-chocolate.jpg"
  },
  "petit-gateau-caseiro": {
    "url": "/recipe-art/petit-gateau-caseiro.jpg"
  },
  "espetinho-frutas-chocolate": {
    "url": "/recipe-art/espetinho-frutas-chocolate.jpg"
  },
  "rocambole-chocolate-morango": {
    "url": "/recipe-art/rocambole-chocolate-morango.jpg"
  },
  "geladinho-chocolate": {
    "url": "/recipe-art/geladinho-chocolate.jpg"
  },
  "sorvete-cremoso-morango-sem-sorveteira": {
    "url": "/recipe-art/sorvete-cremoso-morango-sem-sorveteira.jpg"
  },
  "beijinho-chocolate": {
    "url": "/recipe-art/beijinho-chocolate.jpg"
  },
  "romeu-julieta-goiaba-queijo": {
    "url": "/recipe-art/romeu-julieta-goiaba-queijo.jpg"
  },
  "bolo-chocolate-airfryer": {
    "url": "/recipe-art/bolo-chocolate-airfryer.jpg"
  },
  "torrada-doce-canela-acucar": {
    "url": "/recipe-art/torrada-doce-canela-acucar.jpg"
  },
  "iogurte-caseiro-natural": {
    "url": "/recipe-art/iogurte-caseiro-natural.jpg"
  },
  "caipirinha": {
    "url": "/recipe-art/caipirinha.jpg"
  },
  "caipiroska": {
    "url": "/recipe-art/caipiroska.jpg"
  },
  "caipifruta-morango": {
    "url": "/recipe-art/caipifruta-morango.jpg"
  },
  "mojito": {
    "url": "/recipe-art/mojito.jpg"
  },
  "daiquiri": {
    "url": "/recipe-art/daiquiri.jpg"
  },
  "margarita": {
    "url": "/recipe-art/margarita.jpg"
  },
  "tequila-sunrise": {
    "url": "/recipe-art/tequila-sunrise.jpg"
  },
  "paloma": {
    "url": "/recipe-art/paloma.jpg"
  },
  "negroni": {
    "url": "/recipe-art/negroni.jpg"
  },
  "gin-tonica": {
    "url": "/recipe-art/gin-tonica.jpg"
  },
  "tom-collins": {
    "url": "/recipe-art/tom-collins.jpg"
  },
  "dry-martini": {
    "url": "/recipe-art/dry-martini.jpg"
  },
  "cuba-libre": {
    "url": "/recipe-art/cuba-libre.jpg"
  },
  "pina-colada": {
    "url": "/recipe-art/pina-colada.jpg"
  },
  "moscow-mule": {
    "url": "/recipe-art/moscow-mule.jpg"
  },
  "cosmopolitan": {
    "url": "/recipe-art/cosmopolitan.jpg"
  },
  "bay-breeze": {
    "url": "/recipe-art/bay-breeze.jpg"
  },
  "screwdriver": {
    "url": "/recipe-art/screwdriver.jpg"
  },
  "aperol-spritz": {
    "url": "/recipe-art/aperol-spritz.jpg"
  },
  "campari-spritz": {
    "url": "/recipe-art/campari-spritz.jpg"
  },
  "americano-cocktail": {
    "url": "/recipe-art/americano-cocktail.jpg"
  },
  "garibaldi": {
    "url": "/recipe-art/garibaldi.jpg"
  },
  "whisky-sour": {
    "url": "/recipe-art/whisky-sour.jpg"
  },
  "old-fashioned": {
    "url": "/recipe-art/old-fashioned.jpg"
  },
  "perfect-manhattan": {
    "url": "/recipe-art/perfect-manhattan.jpg"
  },
  "sidecar": {
    "url": "/recipe-art/sidecar.jpg"
  },
  "espresso-martini": {
    "url": "/recipe-art/espresso-martini.jpg"
  },
  "white-russian": {
    "url": "/recipe-art/white-russian.jpg"
  },
  "sangria-tinta": {
    "url": "/recipe-art/sangria-tinta.jpg"
  },
  "batida-de-coco": {
    "url": "/recipe-art/batida-de-coco.jpg"
  },
  "batida-de-maracuja": {
    "url": "/recipe-art/batida-de-maracuja.jpg"
  },
  "batida-de-morango": {
    "url": "/recipe-art/batida-de-morango.jpg"
  },
  "batida-de-amendoim": {
    "url": "/recipe-art/batida-de-amendoim.jpg"
  },
  "caipirinha-frozen": {
    "url": "/recipe-art/caipirinha-frozen.jpg"
  },
  "margarita-frozen": {
    "url": "/recipe-art/margarita-frozen.jpg"
  },
  "daiquiri-morango-frozen": {
    "url": "/recipe-art/daiquiri-morango-frozen.jpg"
  },
  "pina-colada-frozen": {
    "url": "/recipe-art/pina-colada-frozen.jpg"
  },
  "frozen-de-manga": {
    "url": "/recipe-art/frozen-de-manga.jpg"
  },
  "frozen-de-melancia": {
    "url": "/recipe-art/frozen-de-melancia.jpg"
  },
  "clericot-batido": {
    "url": "/recipe-art/clericot-batido.jpg"
  },
  "sangria-branca": {
    "url": "/recipe-art/sangria-branca.jpg"
  },
  "batida-de-cafe": {
    "url": "/recipe-art/batida-de-cafe.jpg"
  },
  "frozen-de-cassis": {
    "url": "/recipe-art/frozen-de-cassis.jpg"
  },
  "batida-de-banana": {
    "url": "/recipe-art/batida-de-banana.jpg"
  },
  "virgin-mojito": {
    "url": "/recipe-art/virgin-mojito.jpg"
  },
  "virgin-colada": {
    "url": "/recipe-art/virgin-colada.jpg"
  },
  "shirley-temple": {
    "url": "/recipe-art/shirley-temple.jpg"
  },
  "virgin-tonic": {
    "url": "/recipe-art/virgin-tonic.jpg"
  }
};
