// Auto-generated by scripts/fetch-recipe-images.mjs — do not hand-edit.
// Photos courtesy of Pexels (https://www.pexels.com), free to use under the Pexels License.

export interface RecipeImage {
  url: string;
  photographer: string;
  photographerUrl: string;
}

export const RECIPE_IMAGES: Record<string, RecipeImage> = {
  "arroz-feijao-simples": {
    "url": "https://images.pexels.com/photos/19781592/pexels-photo-19781592.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lucas Andrade",
    "photographerUrl": "https://www.pexels.com/@lucasandrade"
  },
  "feijao-preto-temperado": {
    "url": "https://images.pexels.com/photos/19781592/pexels-photo-19781592.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lucas Andrade",
    "photographerUrl": "https://www.pexels.com/@lucasandrade"
  },
  "frango-grelhado-limao": {
    "url": "https://images.pexels.com/photos/16845749/pexels-photo-16845749.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Huzaifa Bukhari",
    "photographerUrl": "https://www.pexels.com/@huzaifabukhari"
  },
  "frango-milanesa": {
    "url": "https://images.pexels.com/photos/4078178/pexels-photo-4078178.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Anna Guerrero",
    "photographerUrl": "https://www.pexels.com/@anna-guerrero-788383"
  },
  "frango-xadrez": {
    "url": "https://images.pexels.com/photos/24738520/pexels-photo-24738520.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nadin Sh",
    "photographerUrl": "https://www.pexels.com/@nadin-sh-78971847"
  },
  "frango-curry": {
    "url": "https://images.pexels.com/photos/5835339/pexels-photo-5835339.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tim  Samuel",
    "photographerUrl": "https://www.pexels.com/@tim-samuel"
  },
  "coxa-frango-assada": {
    "url": "https://images.pexels.com/photos/5704254/pexels-photo-5704254.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Bulat Khamitov",
    "photographerUrl": "https://www.pexels.com/@bulat"
  },
  "bife-acebolado": {
    "url": "https://images.pexels.com/photos/36669799/pexels-photo-36669799.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mohamed  Olwy",
    "photographerUrl": "https://www.pexels.com/@mohamed9380"
  },
  "picadinho-carne": {
    "url": "https://images.pexels.com/photos/34822475/pexels-photo-34822475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "SAMY PHOTOGRAPHY",
    "photographerUrl": "https://www.pexels.com/@samy-photography-2157582079"
  },
  "carne-panela": {
    "url": "https://images.pexels.com/photos/34837746/pexels-photo-34837746.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Caleb Oquendo",
    "photographerUrl": "https://www.pexels.com/@caleboquendo"
  },
  "escondidinho-carne-seca": {
    "url": "https://images.pexels.com/photos/33457928/pexels-photo-33457928.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mike Norris",
    "photographerUrl": "https://www.pexels.com/@miken"
  },
  "bacon-ovos": {
    "url": "https://images.pexels.com/photos/1412010/pexels-photo-1412010.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "freestocks.org",
    "photographerUrl": "https://www.pexels.com/@freestocks"
  },
  "omelete-queijo": {
    "url": "https://images.pexels.com/photos/15801901/pexels-photo-15801901.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Eduardo Krajan",
    "photographerUrl": "https://www.pexels.com/@eduardo-krajan-424982200"
  },
  "ovos-mexidos-tomate": {
    "url": "https://images.pexels.com/photos/30855418/pexels-photo-30855418.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Markus Winkler",
    "photographerUrl": "https://www.pexels.com/@markus-winkler-1430818"
  },
  "salsicha-acebolada": {
    "url": "https://images.pexels.com/photos/37275061/pexels-photo-37275061.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "cami",
    "photographerUrl": "https://www.pexels.com/@casnafu"
  },
  "linguica-acebolada": {
    "url": "https://images.pexels.com/photos/533325/pexels-photo-533325.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Pixabay",
    "photographerUrl": "https://www.pexels.com/@pixabay"
  },
  "costela-barbecue": {
    "url": "https://images.pexels.com/photos/8250702/pexels-photo-8250702.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Julia Filirovska",
    "photographerUrl": "https://www.pexels.com/@filirovska"
  },
  "lombo-assado-batatas": {
    "url": "https://images.pexels.com/photos/37025108/pexels-photo-37025108.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Christian Bolaños",
    "photographerUrl": "https://www.pexels.com/@christian-bolanos-2158732257"
  },
  "peixe-frito": {
    "url": "https://images.pexels.com/photos/8250421/pexels-photo-8250421.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Julia Filirovska",
    "photographerUrl": "https://www.pexels.com/@filirovska"
  },
  "peixe-assado-limao": {
    "url": "https://images.pexels.com/photos/12653380/pexels-photo-12653380.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Sylwester Ficek",
    "photographerUrl": "https://www.pexels.com/@sylwester-ficek-154797634"
  },
  "salmao-grelhado": {
    "url": "https://images.pexels.com/photos/36734954/pexels-photo-36734954.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mohamed  Olwy",
    "photographerUrl": "https://www.pexels.com/@mohamed9380"
  },
  "atum-macarrao": {
    "url": "https://images.pexels.com/photos/19302562/pexels-photo-19302562.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nadin Sh",
    "photographerUrl": "https://www.pexels.com/@nadin-sh-78971847"
  },
  "sardinha-panela": {
    "url": "https://images.pexels.com/photos/6399813/pexels-photo-6399813.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "alleksana",
    "photographerUrl": "https://www.pexels.com/@alleksana"
  },
  "camarao-alho-oleo": {
    "url": "https://images.pexels.com/photos/8633745/pexels-photo-8633745.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vilnis Husko",
    "photographerUrl": "https://www.pexels.com/@vhusko"
  },
  "moqueca-simples": {
    "url": "https://images.pexels.com/photos/37099829/pexels-photo-37099829.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Lionel Ntasano",
    "photographerUrl": "https://www.pexels.com/@lionel-ntasano-2160935120"
  },
  "macarrao-alho-oleo": {
    "url": "https://images.pexels.com/photos/4190997/pexels-photo-4190997.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Javier Disabato",
    "photographerUrl": "https://www.pexels.com/@javier-disabato-2612346"
  },
  "macarrao-sugo": {
    "url": "https://images.pexels.com/photos/36430170/pexels-photo-36430170.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Willians Huerta",
    "photographerUrl": "https://www.pexels.com/@willians-huerta-2157111846"
  },
  "macarrao-frango": {
    "url": "https://images.pexels.com/photos/12001950/pexels-photo-12001950.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Towfiqu barbhuiya",
    "photographerUrl": "https://www.pexels.com/@towfiqu-barbhuiya-3440682"
  },
  "nhoque-batata": {
    "url": "https://images.pexels.com/photos/5451005/pexels-photo-5451005.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Erna Daalman",
    "photographerUrl": "https://www.pexels.com/@erna-daalman-95495"
  },
  "risoto-frango": {
    "url": "https://images.pexels.com/photos/17402673/pexels-photo-17402673.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nadin Sh",
    "photographerUrl": "https://www.pexels.com/@nadin-sh-78971847"
  },
  "arroz-forno": {
    "url": "https://images.pexels.com/photos/7625714/pexels-photo-7625714.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Varun Chandak",
    "photographerUrl": "https://www.pexels.com/@vrnchndk"
  },
  "feijoada-simplificada": {
    "url": "https://images.pexels.com/photos/34442361/pexels-photo-34442361.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Laura oliveira",
    "photographerUrl": "https://www.pexels.com/@laura-oliveira-2156849568"
  },
  "sopa-legumes": {
    "url": "https://images.pexels.com/photos/8738017/pexels-photo-8738017.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Farhad Ibrahimzade",
    "photographerUrl": "https://www.pexels.com/@farhad"
  },
  "canja-galinha": {
    "url": "https://images.pexels.com/photos/36852245/pexels-photo-36852245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Yafie Agha",
    "photographerUrl": "https://www.pexels.com/@yafie-agha-507873364"
  },
  "pure-batata": {
    "url": "https://images.pexels.com/photos/13422423/pexels-photo-13422423.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mateusz Feliksik",
    "photographerUrl": "https://www.pexels.com/@mateusz-feliksik-1896604"
  },
  "batata-doce-assada": {
    "url": "https://images.pexels.com/photos/4617528/pexels-photo-4617528.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Damir Mijailovic",
    "photographerUrl": "https://www.pexels.com/@damir-mijailovic-1921088"
  },
  "legumes-refogados": {
    "url": "https://images.pexels.com/photos/5848426/pexels-photo-5848426.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Polina Tankilevitch",
    "photographerUrl": "https://www.pexels.com/@polina-tankilevitch"
  },
  "abobrinha-recheada": {
    "url": "https://images.pexels.com/photos/38501031/pexels-photo-38501031.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Kally Dru",
    "photographerUrl": "https://www.pexels.com/@kallydru"
  },
  "berinjela-parmegiana": {
    "url": "https://images.pexels.com/photos/1707917/pexels-photo-1707917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Melanie Dompierre",
    "photographerUrl": "https://www.pexels.com/@skilletsandpots"
  },
  "salada-tomate-cebola": {
    "url": "https://images.pexels.com/photos/7954590/pexels-photo-7954590.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tamanna Rumee",
    "photographerUrl": "https://www.pexels.com/@tamanna-rumee-52377920"
  },
  "salada-verde": {
    "url": "https://images.pexels.com/photos/36285423/pexels-photo-36285423.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Victoria Bowers",
    "photographerUrl": "https://www.pexels.com/@victoria-bowers-148548814"
  },
  "salada-grao-bico": {
    "url": "https://images.pexels.com/photos/35369047/pexels-photo-35369047.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vural Yavas",
    "photographerUrl": "https://www.pexels.com/@vuralyavas"
  },
  "salada-atum": {
    "url": "https://images.pexels.com/photos/19572488/pexels-photo-19572488.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tuğba ÖZTÜRK",
    "photographerUrl": "https://www.pexels.com/@tugba-ozturk-368300535"
  },
  "vinagrete": {
    "url": "https://images.pexels.com/photos/26152679/pexels-photo-26152679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Valeria Boltneva",
    "photographerUrl": "https://www.pexels.com/@valeriya"
  },
  "farofa-simples": {
    "url": "https://images.pexels.com/photos/7543161/pexels-photo-7543161.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Daniel Dan",
    "photographerUrl": "https://www.pexels.com/@daniel-dan-47825192"
  },
  "polenta-cremosa": {
    "url": "https://images.pexels.com/photos/921362/pexels-photo-921362.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Alex Favali",
    "photographerUrl": "https://www.pexels.com/@puntoitalia"
  },
  "pipoca-simples": {
    "url": "https://images.pexels.com/photos/13005068/pexels-photo-13005068.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Srattha Nualsate",
    "photographerUrl": "https://www.pexels.com/@srattha-nualsate-2695613"
  },
  "aveia-banana": {
    "url": "https://images.pexels.com/photos/6050721/pexels-photo-6050721.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vegan Liftz",
    "photographerUrl": "https://www.pexels.com/@veganliftz"
  },
  "salada-frutas": {
    "url": "https://images.pexels.com/photos/34618713/pexels-photo-34618713.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Novkov Visuals",
    "photographerUrl": "https://www.pexels.com/@novkov-visuals"
  },
  "vitamina-abacate": {
    "url": "https://images.pexels.com/photos/16096610/pexels-photo-16096610.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ngoc Binh Ha",
    "photographerUrl": "https://www.pexels.com/@ngoc-binh-ha-200617504"
  },
  "macarrao-molho-branco": {
    "url": "https://images.pexels.com/photos/1438672/pexels-photo-1438672.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Engin Akyurt",
    "photographerUrl": "https://www.pexels.com/@enginakyurt"
  },
  "frango-barbecue": {
    "url": "https://images.pexels.com/photos/13422453/pexels-photo-13422453.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mateusz Feliksik",
    "photographerUrl": "https://www.pexels.com/@mateusz-feliksik-1896604"
  },
  "costelinha-agridoce": {
    "url": "https://images.pexels.com/photos/5848495/pexels-photo-5848495.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Polina Tankilevitch",
    "photographerUrl": "https://www.pexels.com/@polina-tankilevitch"
  },
  "salpicao-frango": {
    "url": "https://images.pexels.com/photos/17692201/pexels-photo-17692201.png?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Đức Trung Đào",
    "photographerUrl": "https://www.pexels.com/@macnalodao"
  },
  "omelete-espinafre": {
    "url": "https://images.pexels.com/photos/5639284/pexels-photo-5639284.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Shameel mukkath",
    "photographerUrl": "https://www.pexels.com/@shameel-mukkath-3421394"
  },
  "sopa-ervilha": {
    "url": "https://images.pexels.com/photos/24186408/pexels-photo-24186408.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Change C.C",
    "photographerUrl": "https://www.pexels.com/@change-c-c-974768353"
  },
  "risoto-camarao": {
    "url": "https://images.pexels.com/photos/23627779/pexels-photo-23627779.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Rudi Kessler",
    "photographerUrl": "https://www.pexels.com/@rudi-kessler-1264051470"
  },
  "sufle-brocolis": {
    "url": "https://images.pexels.com/photos/6732303/pexels-photo-6732303.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Asya Vlasova",
    "photographerUrl": "https://www.pexels.com/@asya-vlasova-228168"
  },
  "couve-refogada": {
    "url": "https://images.pexels.com/photos/9219076/pexels-photo-9219076.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Loren Castillo",
    "photographerUrl": "https://www.pexels.com/@lorencastillo"
  },
  "salada-repolho": {
    "url": "https://images.pexels.com/photos/7362673/pexels-photo-7362673.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Engin Akyurt",
    "photographerUrl": "https://www.pexels.com/@enginakyurt"
  },
  "palmito-molho-branco": {
    "url": "https://images.pexels.com/photos/33042510/pexels-photo-33042510.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Meliha Ljaljic",
    "photographerUrl": "https://www.pexels.com/@meliha-ljaljic-305648550"
  },
  "salada-palmito": {
    "url": "https://images.pexels.com/photos/29208501/pexels-photo-29208501.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Fernanda da Silva Lopes",
    "photographerUrl": "https://www.pexels.com/@fernanda-da-silva-lopes-2055473628"
  },
  "brigadeiro": {
    "url": "https://images.pexels.com/photos/38441749/pexels-photo-38441749.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Rafael Rodrigues",
    "photographerUrl": "https://www.pexels.com/@rrodriguesim"
  },
  "bolo-cenoura-chocolate": {
    "url": "https://images.pexels.com/photos/20859567/pexels-photo-20859567.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "kublizz",
    "photographerUrl": "https://www.pexels.com/@kublizz-550505632"
  },
  "bolo-chocolate-molhadinho": {
    "url": "https://images.pexels.com/photos/10249461/pexels-photo-10249461.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nishant Sharma",
    "photographerUrl": "https://www.pexels.com/@nishant-sharma-77755298"
  },
  "pudim-leite-condensado": {
    "url": "https://images.pexels.com/photos/10918153/pexels-photo-10918153.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "SimplyArt4794",
    "photographerUrl": "https://www.pexels.com/@simplyart4794-53798833"
  },
  "bolinho-chuva": {
    "url": "https://images.pexels.com/photos/14505999/pexels-photo-14505999.png?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Marvin Corea",
    "photographerUrl": "https://www.pexels.com/@iumoo"
  },
  "bolo-fuba-cremoso": {
    "url": "https://images.pexels.com/photos/34637996/pexels-photo-34637996.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Alejandro JV",
    "photographerUrl": "https://www.pexels.com/@vivanpunk"
  },
  "pao-de-queijo": {
    "url": "https://images.pexels.com/photos/20450299/pexels-photo-20450299.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "thiago japyassu",
    "photographerUrl": "https://www.pexels.com/@japy"
  },
  "coxinha-frango": {
    "url": "https://images.pexels.com/photos/27609407/pexels-photo-27609407.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Leonardo Aquino",
    "photographerUrl": "https://www.pexels.com/@leonardo-aquino-246345118"
  },
  "misto-quente": {
    "url": "https://images.pexels.com/photos/8023677/pexels-photo-8023677.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mateusz Feliksik",
    "photographerUrl": "https://www.pexels.com/@mateusz-feliksik-1896604"
  },
  "pastel-forno-carne": {
    "url": "https://images.pexels.com/photos/22764448/pexels-photo-22764448.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Andres Alaniz",
    "photographerUrl": "https://www.pexels.com/@andres-alaniz-461433202"
  },
  "lasanha-bolonhesa": {
    "url": "https://images.pexels.com/photos/13823542/pexels-photo-13823542.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "素材王国 Footage Kingdom",
    "photographerUrl": "https://www.pexels.com/@footage-kingdom-122917970"
  },
  "panqueca-carne-moida": {
    "url": "https://images.pexels.com/photos/11094167/pexels-photo-11094167.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Hiure Gomes Fernandes",
    "photographerUrl": "https://www.pexels.com/@hiure-gomes-fernandes-1309965"
  },
  "torta-frango-liquidificador": {
    "url": "https://images.pexels.com/photos/10885316/pexels-photo-10885316.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Midtrack -",
    "photographerUrl": "https://www.pexels.com/@midtrack"
  },
  "chocolate-quente-cremoso": {
    "url": "https://images.pexels.com/photos/1839882/pexels-photo-1839882.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Isaiah Quindo",
    "photographerUrl": "https://www.pexels.com/@isaiah-quindo-924057"
  },
  "suco-laranja-natural": {
    "url": "https://images.pexels.com/photos/14510445/pexels-photo-14510445.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Rae  Wallis",
    "photographerUrl": "https://www.pexels.com/@raewallis"
  },
  "vitamina-banana": {
    "url": "https://images.pexels.com/photos/28525197/pexels-photo-28525197.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Alejandro Aznar",
    "photographerUrl": "https://www.pexels.com/@alejandro-aznar-155337093"
  },
  "suco-verde-detox": {
    "url": "https://images.pexels.com/photos/4443434/pexels-photo-4443434.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Polina Tankilevitch",
    "photographerUrl": "https://www.pexels.com/@polina-tankilevitch"
  },
  "cocada-cremosa": {
    "url": "https://images.pexels.com/photos/38441742/pexels-photo-38441742.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Rafael Rodrigues",
    "photographerUrl": "https://www.pexels.com/@rrodriguesim"
  },
  "beijinho": {
    "url": "https://images.pexels.com/photos/33643879/pexels-photo-33643879.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Rafael Rodrigues",
    "photographerUrl": "https://www.pexels.com/@rrodriguesim"
  },
  "mousse-chocolate": {
    "url": "https://images.pexels.com/photos/3810779/pexels-photo-3810779.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Vladimir Srajber",
    "photographerUrl": "https://www.pexels.com/@vladimirsrajber"
  },
  "danoninho-caseiro": {
    "url": "https://images.pexels.com/photos/7474043/pexels-photo-7474043.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Valeria Boltneva",
    "photographerUrl": "https://www.pexels.com/@valeriya"
  },
  "sanduiche-natural-frango": {
    "url": "https://images.pexels.com/photos/5446516/pexels-photo-5446516.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Farhad Ibrahimzade",
    "photographerUrl": "https://www.pexels.com/@farhad"
  },
  "pizza-liquidificador": {
    "url": "https://images.pexels.com/photos/31596394/pexels-photo-31596394.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Sonali Mehta",
    "photographerUrl": "https://www.pexels.com/@sonali-mehta-1514525371"
  },
  "arroz-doce": {
    "url": "https://images.pexels.com/photos/20488815/pexels-photo-20488815.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Gül Işık",
    "photographerUrl": "https://www.pexels.com/@ekrulila"
  },
  "frango-assado-ervas": {
    "url": "https://images.pexels.com/photos/7900353/pexels-photo-7900353.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Conny Querales",
    "photographerUrl": "https://www.pexels.com/@conny-querales-69051"
  },
  "picanha-chapa": {
    "url": "https://images.pexels.com/photos/20896462/pexels-photo-20896462.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Daniel Januario",
    "photographerUrl": "https://www.pexels.com/@daniel-januario-1127884405"
  },
  "carne-sol-abobora-coentro": {
    "url": "https://images.pexels.com/photos/30635695/pexels-photo-30635695.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "IARA MELO",
    "photographerUrl": "https://www.pexels.com/@iara-melo-558346607"
  },
  "carne-porco-refogada-cominho": {
    "url": "https://images.pexels.com/photos/724294/pexels-photo-724294.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Cats Coming",
    "photographerUrl": "https://www.pexels.com/@catscoming"
  },
  "pernil-assado-alecrim": {
    "url": "https://images.pexels.com/photos/10710973/pexels-photo-10710973.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Cleo Vergara",
    "photographerUrl": "https://www.pexels.com/@cleov"
  },
  "mortadela-chapa": {
    "url": "https://images.pexels.com/photos/8023677/pexels-photo-8023677.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mateusz Feliksik",
    "photographerUrl": "https://www.pexels.com/@mateusz-feliksik-1896604"
  },
  "figado-acebolado": {
    "url": "https://images.pexels.com/photos/8696528/pexels-photo-8696528.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Farhad Ibrahimzade",
    "photographerUrl": "https://www.pexels.com/@farhad"
  },
  "peru-assado-natal": {
    "url": "https://images.pexels.com/photos/6210774/pexels-photo-6210774.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tim Douglas",
    "photographerUrl": "https://www.pexels.com/@tim-douglas"
  },
  "posta-atum-grelhado": {
    "url": "https://images.pexels.com/photos/27662770/pexels-photo-27662770.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Enzo Iorio",
    "photographerUrl": "https://www.pexels.com/@enzo-iorio-381015179"
  },
  "arroz-integral-legumes": {
    "url": "https://images.pexels.com/photos/9219098/pexels-photo-9219098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Loren Castillo",
    "photographerUrl": "https://www.pexels.com/@lorencastillo"
  },
  "feijao-fradinho-bacon": {
    "url": "https://images.pexels.com/photos/29269763/pexels-photo-29269763.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Diet Guide",
    "photographerUrl": "https://www.pexels.com/@diet-guide-2072911832"
  },
  "salada-lentilha-legumes": {
    "url": "https://images.pexels.com/photos/6145899/pexels-photo-6145899.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Anna Pyshniuk",
    "photographerUrl": "https://www.pexels.com/@anna-pyshniuk-2453945"
  },
  "salada-quinoa-grao-bico": {
    "url": "https://images.pexels.com/photos/38499046/pexels-photo-38499046.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mohammed-Ali  Hamadache",
    "photographerUrl": "https://www.pexels.com/@mohammed-ali-hamadache-2158253558"
  },
  "salada-milho-ervilha": {
    "url": "https://images.pexels.com/photos/11704890/pexels-photo-11704890.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Tom Tran",
    "photographerUrl": "https://www.pexels.com/@tom-tran-1199646"
  },
  "sardinha-enlatada-cebola-tomate": {
    "url": "https://images.pexels.com/photos/6399813/pexels-photo-6399813.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "alleksana",
    "photographerUrl": "https://www.pexels.com/@alleksana"
  },
  "feijao-grao-bico-enlatados": {
    "url": "https://images.pexels.com/photos/30168757/pexels-photo-30168757.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Anthony Rahayel",
    "photographerUrl": "https://www.pexels.com/@anthony-rahayel-125801377"
  },
  "salpicao-seleta-legumes": {
    "url": "https://images.pexels.com/photos/19904309/pexels-photo-19904309.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ayberk Mirza",
    "photographerUrl": "https://www.pexels.com/@holoshuriken"
  },
  "strogonoff-cogumelos": {
    "url": "https://images.pexels.com/photos/29935503/pexels-photo-29935503.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "khezez  | خزاز",
    "photographerUrl": "https://www.pexels.com/@khezez"
  },
  "pessego-calda-creme": {
    "url": "https://images.pexels.com/photos/9093554/pexels-photo-9093554.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Matthew Osier",
    "photographerUrl": "https://www.pexels.com/@matthew-osier-90237472"
  },
  "bolo-laranja-margarina": {
    "url": "https://images.pexels.com/photos/30700690/pexels-photo-30700690.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Change C.C",
    "photographerUrl": "https://www.pexels.com/@change-c-c-974768353"
  },
  "peixe-molho-acafrao": {
    "url": "https://images.pexels.com/photos/19480560/pexels-photo-19480560.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nadin Sh",
    "photographerUrl": "https://www.pexels.com/@nadin-sh-78971847"
  },
  "limonada-hortela": {
    "url": "https://images.pexels.com/photos/18142599/pexels-photo-18142599.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Denys Gromov",
    "photographerUrl": "https://www.pexels.com/@jdgromov"
  },
  "frango-empanado-alho-po": {
    "url": "https://images.pexels.com/photos/7172851/pexels-photo-7172851.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Gabriela Sakita",
    "photographerUrl": "https://www.pexels.com/@gabriela-sakita-2047260"
  },
  "compota-maca-cravo-canela": {
    "url": "https://images.pexels.com/photos/39354/apple-peeler-fruit-green-39354.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Pixabay",
    "photographerUrl": "https://www.pexels.com/@pixabay"
  },
  "pure-batata-noz-moscada": {
    "url": "https://images.pexels.com/photos/13422423/pexels-photo-13422423.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mateusz Feliksik",
    "photographerUrl": "https://www.pexels.com/@mateusz-feliksik-1896604"
  },
  "batata-rustica-paprica": {
    "url": "https://images.pexels.com/photos/38104324/pexels-photo-38104324.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Muhammad  Khawar Nazir",
    "photographerUrl": "https://www.pexels.com/@drmkhawarnazir"
  },
  "macarrao-molho-rose": {
    "url": "https://images.pexels.com/photos/16525900/pexels-photo-16525900.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "The Qurious Studio",
    "photographerUrl": "https://www.pexels.com/@the-qurious-studio-537664004"
  },
  "macarrao-pesto": {
    "url": "https://images.pexels.com/photos/4748540/pexels-photo-4748540.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Regina Ferraz",
    "photographerUrl": "https://www.pexels.com/@reginaferraz"
  },
  "bife-molho-ingles": {
    "url": "https://images.pexels.com/photos/3660/food-restaurant-dinner-lunch.jpg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "JÉSHOOTS",
    "photographerUrl": "https://www.pexels.com/@jeshoots"
  },
  "frango-molho-pimenta-mel": {
    "url": "https://images.pexels.com/photos/7788312/pexels-photo-7788312.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Ivan Babydov",
    "photographerUrl": "https://www.pexels.com/@babydov"
  },
  "pao-alho-molho-alho": {
    "url": "https://images.pexels.com/photos/13062441/pexels-photo-13062441.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "nikhil bali",
    "photographerUrl": "https://www.pexels.com/@nikhil-bali-284427335"
  },
  "salada-vinagrete-simples": {
    "url": "https://images.pexels.com/photos/6653877/pexels-photo-6653877.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Arina Krasnikova",
    "photographerUrl": "https://www.pexels.com/@arina-krasnikova"
  },
  "sopa-raizes": {
    "url": "https://images.pexels.com/photos/9218652/pexels-photo-9218652.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Loren Castillo",
    "photographerUrl": "https://www.pexels.com/@lorencastillo"
  },
  "refogado-folhas-variadas": {
    "url": "https://images.pexels.com/photos/36108993/pexels-photo-36108993.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Yuen Tou  Zan",
    "photographerUrl": "https://www.pexels.com/@tochtliyeung1996"
  },
  "legumes-assados-ervas-2": {
    "url": "https://images.pexels.com/photos/6969712/pexels-photo-6969712.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "cottonbro studio",
    "photographerUrl": "https://www.pexels.com/@cottonbro"
  },
  "quiabo-jilo-refogados": {
    "url": "https://images.pexels.com/photos/35041666/pexels-photo-35041666.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Milton Das",
    "photographerUrl": "https://www.pexels.com/@miltonphotography"
  },
  "salada-rabanete-gengibre": {
    "url": "https://images.pexels.com/photos/34298925/pexels-photo-34298925.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jonathan Borba",
    "photographerUrl": "https://www.pexels.com/@jonathanborba"
  },
  "salada-tropical-frutas": {
    "url": "https://images.pexels.com/photos/5620860/pexels-photo-5620860.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Anna Tarazevich",
    "photographerUrl": "https://www.pexels.com/@anntarazevich"
  },
  "compota-frutas-vermelhas": {
    "url": "https://images.pexels.com/photos/32726592/pexels-photo-32726592.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "TimePRO TV",
    "photographerUrl": "https://www.pexels.com/@timepro-tv-2148736540"
  },
  "suco-detox-caju-acerola": {
    "url": "https://images.pexels.com/photos/17612822/pexels-photo-17612822.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Shameel mukkath",
    "photographerUrl": "https://www.pexels.com/@shameel-mukkath-3421394"
  },
  "salada-frutas-goiaba-pessego-lichia": {
    "url": "https://images.pexels.com/photos/35532842/pexels-photo-35532842.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "athul santhosh",
    "photographerUrl": "https://www.pexels.com/@athul-santhosh-1483733062"
  },
  "sobrecoxa-assada": {
    "url": "https://images.pexels.com/photos/145804/pexels-photo-145804.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "freestocks.org",
    "photographerUrl": "https://www.pexels.com/@freestocks"
  },
  "asa-frango-mel-soja": {
    "url": "https://images.pexels.com/photos/16444394/pexels-photo-16444394.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Dextar Studio ™",
    "photographerUrl": "https://www.pexels.com/@dextarstudio"
  },
  "coracao-frango-espeto": {
    "url": "https://images.pexels.com/photos/15125028/pexels-photo-15125028.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jimmy Liao",
    "photographerUrl": "https://www.pexels.com/@jimmy-liao-3615017"
  },
  "file-mignon-ervas": {
    "url": "https://images.pexels.com/photos/4001870/pexels-photo-4001870.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Dima Valkov",
    "photographerUrl": "https://www.pexels.com/@dima-valkov-1186343"
  },
  "patinho-molho-cebola": {
    "url": "https://images.pexels.com/photos/31779547/pexels-photo-31779547.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Adriano Bragi",
    "photographerUrl": "https://www.pexels.com/@adriano-bragi-1288014591"
  },
  "contrafile-chapa": {
    "url": "https://images.pexels.com/photos/36683024/pexels-photo-36683024.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Mohamed  Olwy",
    "photographerUrl": "https://www.pexels.com/@mohamed9380"
  },
  "maminha-assada": {
    "url": "https://images.pexels.com/photos/27643019/pexels-photo-27643019.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nano Erdozain",
    "photographerUrl": "https://www.pexels.com/@nano-erdozain-120534369"
  },
  "fraldinha-churrasqueira": {
    "url": "https://images.pexels.com/photos/7613561/pexels-photo-7613561.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Los Muertos Crew",
    "photographerUrl": "https://www.pexels.com/@cristian-rojas"
  },
  "cupim-panela-pressao": {
    "url": "https://images.pexels.com/photos/37794985/pexels-photo-37794985.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Jay Moon",
    "photographerUrl": "https://www.pexels.com/@jay-moon-2149536798"
  },
  "lagarto-rosbife-mostarda": {
    "url": "https://images.pexels.com/photos/7741852/pexels-photo-7741852.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Emre Vonal",
    "photographerUrl": "https://www.pexels.com/@emre-vonal-51672462"
  },
  "acem-cozido-legumes": {
    "url": "https://images.pexels.com/photos/34822475/pexels-photo-34822475.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "SAMY PHOTOGRAPHY",
    "photographerUrl": "https://www.pexels.com/@samy-photography-2157582079"
  },
  "musculo-molho-tomate": {
    "url": "https://images.pexels.com/photos/30678525/pexels-photo-30678525.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "one  click",
    "photographerUrl": "https://www.pexels.com/@rafaellenss"
  },
  "costelinha-suina-mel-mostarda": {
    "url": "https://images.pexels.com/photos/34495394/pexels-photo-34495394.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Nobleseed Nobleseed",
    "photographerUrl": "https://www.pexels.com/@nobleseed"
  },
  "panceta-crocante": {
    "url": "https://images.pexels.com/photos/34314497/pexels-photo-34314497.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "ERIVELTO Martins",
    "photographerUrl": "https://www.pexels.com/@erivas"
  },
  "bisteca-grelhada-limao": {
    "url": "https://images.pexels.com/photos/11600756/pexels-photo-11600756.jpeg?auto=compress&cs=tinysrgb&h=650&w=940",
    "photographer": "Timmy Barg",
    "photographerUrl": "https://www.pexels.com/@timmy-barg-153697177"
  }
};
