// Auto-generated by scripts/fetch-tipo-prato-images.mjs — do not hand-edit.
// Photos courtesy of Pexels (https://www.pexels.com), free to use under the Pexels License.

export interface TipoPratoImage {
  url: string;
  photographer: string;
  photographerUrl: string;
}

export const TIPO_PRATO_IMAGES: Record<'doce' | 'salgado', TipoPratoImage> = {
  "doce": {
    "url": "https://images.pexels.com/photos/28728775/pexels-photo-28728775.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "photographer": "Paloma Clarice",
    "photographerUrl": "https://www.pexels.com/@palomaclaricefotografia"
  },
  "salgado": {
    "url": "https://images.pexels.com/photos/9304020/pexels-photo-9304020.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "photographer": "Kaique Lopes",
    "photographerUrl": "https://www.pexels.com/@kaique-lopes-3899395"
  }
};
